In [1]:
import pandas as pd

In [3]:
df   = pd.read_csv('../../property_new.csv')
df

,Unnamed: 0,UniqueID,PropertyAddress,LandUse,SalePrice,SaleDate,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,SoldAsVacant
0,0,2045,"1808 FOX CHASE DR, GOODLETTSVILLE",SINGLE FAMILY,240000,"April 9, 2013",50000.0,168200.0,235700.0,1986.0,3.0,No
1,1,16918,"1832 FOX CHASE DR, GOODLETTSVILLE",SINGLE FAMILY,366000,"June 10, 2014",50000.0,264100.0,319000.0,1998.0,3.0,No
2,2,54582,"1864 FOX CHASE DR, GOODLETTSVILLE",SINGLE FAMILY,435000,"September 26, 2016",50000.0,216200.0,298000.0,1987.0,4.0,No
3,3,43070,"1853 FOX CHASE DR, GOODLETTSVILLE",SINGLE FAMILY,255000,"January 29, 2016",50000.0,147300.0,197300.0,1985.0,3.0,No
4,4,22714,"1829 FOX CHASE DR, GOODLETTSVILLE",SINGLE FAMILY,278000,"October 10, 2014",50000.0,152300.0,202300.0,1984.0,4.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...
56472,56472,30469,"1435 WINDING CREEK DR, NOLENSVILLE",SINGLE FAMILY,157500,"May 27, 2015",NaN,NaN,NaN,NaN,NaN,No
56473,56473,27707,"1423 WINDING CREEK DR, NOLENSVILLE",SINGLE FAMILY,145000,"March 2, 2015",NaN,NaN,NaN,NaN,NaN,No
56474,56474,52709,"1804 GRACE POINT LN, NOLENSVILLE",VACANT RESIDENTIAL LAND,234611,"August 16, 2016",NaN,NaN,NaN,NaN,NaN,Yes
56475,56475,54042,"1709 PARK TERRACE LN, NOLENSVILLE",VACANT RESIDENTIAL LAND,93844,"September 7, 2016",NaN,NaN,NaN,NaN,NaN,Yes
56476,56476,54043,"1713 PARK TERRACE LN, NOLENSVILLE",VACANT RESIDENTIAL LAND,93844,"September 7, 2016",NaN,NaN,NaN,NaN,NaN,Yes

In [ ]:
df